# Generated by Django 2.1.4 on 2018-12-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('token', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('violation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Kampfrichter.Run')),
                ('handoff_ready', models.BooleanField(default=False)),
                ('relay_violation', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kampfrichter.Competition'),
        ),
    ]
