# Generated by Django 2.1.4 on 2018-12-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kampfrichter', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('competition', 'name')},
        ),
    ]
