# Generated by Django 2.1.4 on 2018-12-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kampfrichter', '0002_auto_20181231_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='run',
            unique_together=set(),
        ),
    ]
