# Generated by Django 2.1.4 on 2019-01-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kampfrichter', '0003_auto_20181231_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='age',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='run',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='run',
            name='sex',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
